---
- name: Deploy AS3
  hosts: localhost
  connection: localhost
  gather_facts: no


  vars_files:
    creds.yaml

  tasks:

    - name: Send to BIG-IP
      uri: https://"{{ bigip }}"/mgmt/shared/appsvcs/declare
      method: POST
      user: "{{ bigip_user }}"
      password: "{{ bigip_password }}"
      body: "{{ lookup('file','./as3ansible.json') }}"
      force_basic_auth: yes
      body_format: json
      status_code: 200
      validate_certs: no